# Generated by Django 2.0 on 2021-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='Unit_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Unit_price',
            field=models.IntegerField(),
        ),
    ]
