# Generated by Django 2.0 on 2021-05-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer_id',
            new_name='Customer',
        ),
    ]
