# Generated by Django 2.0 on 2021-05-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210527_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Productsss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
        ),
    ]
